server:
  port: 8080

welcome:
  message: Welcome to the themgi

spring:
  profiles:
    active: qa
---
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/dcbapp
    username: root
    password: ayanali78941
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile: qa

management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/dcbapp
    username: root
    password: ayanali78941
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile: dev